### ISSUE TITLE
Stuck in Connecting...

### ISSUE THREAD

**Issue by diogocarvalho19** [BrettNordin/Exile#13]
Hi, well I have a problem creating my Exile server.
Well it starts all normal, but then when I go connect to the server it gets stuck in "Connecting..."

.rpt log:
https://pastebin.com/LJ1H5Hwu

extDB3 log:
https://pastebin.com/Zk0UkfFi

I'm using a VPS spec:
1 vCore (s)
2.4 GHz
6 GB RAM
25GB + 50GB
Windows Server 2012 R2
x64

Thanks.

**Comment by DoubleRepo** [comment]
I don't want to sound rude here, but Arma is not a server you should run on a VPS. 

Try getting a decent Dedicated server or rent a server at a game hosting provider.

Also your issue doesn't seem to be with ExtDB3.

If you need help with anything Exile related i'd suggest you turn to their forums or discord channel.
https://discord.gg/UyhtEBh

**Comment by BrettNordin** [comment]
Please make sure you have all the ports open to run arms 3 server, this is not an extdb3 issue. Sorry i won't be able to help out more.
