### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by mraxlux** [BrettNordin/Exile#16]
Hey, I did everything on this. but still i have 

12:42:24 CallExtension 'extDB2' could not be found
12:42:24 "ExileServer - MySQL connection error!"
12:42:24 "ExileServer - Please have a look at @ExileServer/extDB/logs/ to find out what went wrong."
12:42:24 "ExileServer - MySQL Error: Unable to locate extDB2 extension!"
12:42:24 "ExileServer - Server will shutdown now :("
12:42:24 CallExtension 'extDB2' could not be found

This error, I have extdb3 in the /arma/ folder.

**Comment by BrettNordin** [comment]
It seems that you still have the old code being called, do you have the exile server overwrites in the config?

Thanks,

Brett

________________________________

**Comment by mraxlux** [comment]
If you want i can show you my server trough teamviewer

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by BrettNordin** [comment]
Please go to the exile discord for more assistance! As I no longer provides support for this addon!

Thanks,

Brett

________________________________
