### ISSUE TITLE
Life Time Deletion Issue

### ISSUE THREAD

**Issue by BrettNordin** [BrettNordin/Exile#4]
Lifetime deletion does not work. I am assuming it has to do with how we are handling the spawned in at and last updated at times. (we are nulling the last updated at). Will look at resolving issue

**Comment by BrettNordin** [comment]
Issue was server was in safemode,
running:
SET SQL_SAFE_UPDATES=0;
Will Fix it.

**Comment by gurulea93** [comment]
For me no working
