### ISSUE TITLE
Field 'assigned_items' doesn't have a default value

### ISSUE THREAD

**Issue by ShadowRanger** [BrettNordin/Exile#7]
So I'm getting the following extDB3 error when a player joins our Exile server:
extDB3: SQL: Error MariaDBStatementException1: Field 'assigned_items' doesn't have a default value

Now I know that you have stated a fix for this under the common errors section, but I really don't want to have to run that SQL command as our MySQL server has several other databases which I don't want to change these strict settings for. Is there any workaround to this?

**Comment by BrettNordin** [comment]
You can solve this issues by going into the database and editing the accounts table. And disableing the notnull setting for the row.

**Comment by Maverick87Shaka** [comment]
@BrettNordin  Can you be more specifc? I have the same problem on a fresh Exile Installation
In the account table I don't have the "assigned_items" column, so I don't know where disable not null option.

Not null option on row I think is pretty impossible on SQL :D

**Comment by MrIce1987** [comment]
I have the problem with the Dantenbak that I can't change it.
It would be very nice if you could send me a suggested solution with instructions

Mistake:
Field 'assigned_items' doesn't have a default value
